services:
  bookasio-tor-dev:
    extends:
      file: ./docker-compose.tor.yml
      service: bookasio-tor
    build:
      context: .
      dockerfile: Dockerfile
      target: cwa-bd-tor
    environment:
      DEBUG: true
      APP_ENV: dev
    volumes:
      - /tmp/cwa-book-downloader:/tmp/cwa-book-downloader
      - /tmp/cwa-book-downloader-log:/var/log/cwa-book-downloader
