services:
  bookasio-dev:
    extends:
      file: ./docker-compose.yml
      service: bookasio
    build:
      context: .
      dockerfile: Dockerfile
      target: cwa-bd
    environment:
      DEBUG: true
      APP_ENV: dev
      USE_DOH: true
      CUSTOM_DNS: cloudflare
    volumes:
      - /tmp/cwa-book-downloader:/tmp/cwa-book-downloader
      - /tmp/cwa-book-downloader-log:/var/log/cwa-book-downloader
